Predict probabilities on all test images using the saved classifier 

In [54]:
import pickle
from os.path import join
import numpy as np
import pandas as pd

pickle_path = join('..', '..', 'pickles')

with open(join(pickle_path, 'classifier_global.pkl'), 'rb') as f:
    clf = pickle.load(f)

In [55]:
regions = ['borde_rural', 'borde_soacha', 'mixco_1_and_ebenezer', 'mixco_3']

Collect all sets of test features and concatenate them into one

In [56]:
columns = ['id', 'features']
df_test_global = pd.DataFrame(columns=columns)

for region in regions:
    try:
        with open(join(pickle_path, 'resnet50_features_' + region + '_test.pkl'), 'rb') as f:
            df_test = pickle.load(f)
            df_test_global = pd.concat([df_test_global, df_test])
    except:
        print("Error reading test data for region ", region)

Error reading test data for region  borde_soacha


Predict the probabilities for every single test example and put them all in a new dataframe

In [57]:
df_test = df_test.head()

columns = ['id', 'pred_prob']
df_results = pd.DataFrame(columns=columns)
data = []

for i, row in df_test_global.iterrows():
    
    features = row['features'].reshape(1, -1)
    pred_prob = clf.predict_proba(features)[0]
    #print(pred_prob)
    
    d = {'id': row['id'], 'pred_prob': pred_prob}
    data.append(d)

df_results = pd.DataFrame(data)
#df_results.features.apply(lambda features: pd.Series(list(features)))

[0.99282006 0.00198769 0.00235915 0.0028331 ]
[0.69562053 0.10121569 0.1905186  0.01264519]
[0.28316852 0.67110334 0.04097727 0.00475088]
[0.0164003  0.31963152 0.6513164  0.01265178]
[0.41470041 0.32954584 0.19880612 0.05694763]
[9.87340227e-01 1.36249190e-04 2.72702472e-04 1.22508211e-02]
[0.98757075 0.00685798 0.00363884 0.00193242]
[0.04368913 0.0937906  0.83767169 0.02484858]
[0.05573645 0.74873322 0.12847194 0.06705839]
[0.36886901 0.5731441  0.04849153 0.00949536]
[0.21918532 0.65550897 0.10035808 0.02494763]
[0.53512018 0.41832521 0.00964307 0.03691155]
[0.99171621 0.00379804 0.00153106 0.00295469]
[0.69524909 0.2835933  0.01871229 0.00244532]
[0.87279929 0.10369327 0.00320817 0.02029927]
[0.49538724 0.45377063 0.04543585 0.00540629]
[0.45038014 0.52051728 0.01282625 0.01627633]
[0.34234346 0.04233708 0.00889507 0.60642439]
[0.8616394  0.12245343 0.01016046 0.00574671]
[0.88724292 0.00741275 0.00634413 0.09900021]
[0.938368   0.04050168 0.01161696 0.00951336]
[0.25577852 0.0434

[0.09159909 0.84622175 0.0568957  0.00528346]
[0.94433812 0.03515745 0.00733225 0.01317219]
[0.09434463 0.20189272 0.65917368 0.04458897]
[9.90699972e-01 5.76369869e-03 5.61736307e-04 2.97459278e-03]
[0.96262216 0.02547683 0.00533366 0.00656735]
[0.85754001 0.09236562 0.0391164  0.01097797]
[0.26107195 0.66368009 0.0242412  0.05100676]
[0.95457147 0.01830548 0.00277511 0.02434795]
[0.18403834 0.26964787 0.04629198 0.5000218 ]
[0.8682258  0.0853717  0.01068114 0.03572136]
[0.9232079  0.05451891 0.00190246 0.02037073]
[0.93765912 0.01047828 0.00136119 0.05050141]
[0.57173255 0.39501384 0.01321043 0.02004318]
[0.41219273 0.03825848 0.53710495 0.01244384]
[0.02560976 0.94595779 0.01835337 0.01007908]
[0.31119463 0.61043418 0.06087622 0.01749498]
[0.14155613 0.58609553 0.23520843 0.03713992]
[0.70378454 0.18375742 0.07333995 0.03911809]
[0.05462279 0.78022907 0.16156544 0.0035827 ]
[0.29997446 0.62719448 0.02206567 0.05076539]
[0.87666299 0.06875442 0.04607284 0.00850975]
[0.49445703 0.3368

[0.80717718 0.0832644  0.05784453 0.05171389]
[0.81461281 0.05970642 0.08737446 0.03830631]
[0.95347343 0.02732236 0.00622926 0.01297494]
[0.86625982 0.06513652 0.03150476 0.0370989 ]
[0.56028715 0.20386772 0.22735982 0.0084853 ]
[0.22997526 0.69863787 0.0517468  0.01964007]
[0.02841465 0.17994949 0.77197275 0.01966312]
[0.96473191 0.0240314  0.00594494 0.00529175]
[0.17456157 0.46860077 0.33479478 0.02204288]
[9.93428392e-01 5.74016109e-04 4.32272191e-03 1.67486954e-03]
[0.05343616 0.69992199 0.05364391 0.19299794]
[0.47910782 0.41995162 0.08520444 0.01573612]
[9.97401756e-01 1.69306971e-04 1.77243635e-03 6.56500912e-04]
[0.08820155 0.56543703 0.33042694 0.01593447]
[0.82522783 0.02633893 0.13651216 0.01192108]
[0.90933053 0.06921308 0.00263574 0.01882065]
[9.94707376e-01 1.84398020e-03 6.88457335e-04 2.76018663e-03]
[0.67378276 0.25912967 0.01001731 0.05707026]
[0.02181342 0.00491783 0.97111841 0.00215034]
[0.20846059 0.14252599 0.63754766 0.01146575]
[0.00688685 0.98165108 0.0057140

[0.108277   0.68475358 0.18302086 0.02394855]
[0.82310977 0.14703255 0.00825971 0.02159796]
[0.86268981 0.02768181 0.10430759 0.00532079]
[0.93965804 0.0501197  0.00186593 0.00835633]
[0.0420316  0.82219525 0.13072137 0.00505178]
[0.28797689 0.57972499 0.12589868 0.00639944]
[0.84978868 0.08767664 0.04130593 0.02122875]
[0.5719392  0.36852736 0.04913564 0.0103978 ]
[0.6667775  0.31382557 0.00818909 0.01120784]
[0.51005626 0.32222446 0.13535212 0.03236716]
[0.68423374 0.25122469 0.01107227 0.0534693 ]
[0.557472   0.36198526 0.0170055  0.06353724]
[0.95980354 0.01540252 0.00296004 0.0218339 ]
[0.59041041 0.10801129 0.22904081 0.07253749]
[0.95959908 0.021768   0.01650489 0.00212804]
[0.50239957 0.3819307  0.05470235 0.06096738]
[0.79637805 0.11025962 0.01355663 0.0798057 ]
[0.98907066 0.00248254 0.00146766 0.00697914]
[0.98606078 0.0041396  0.00314708 0.00665253]
[0.85101604 0.09233467 0.04215453 0.01449476]
[0.7515615  0.22233287 0.01092838 0.01517726]
[0.97295301 0.00648522 0.01569202 

[0.23215491 0.11031611 0.65045463 0.00707436]
[9.95483153e-01 1.22013177e-03 3.03397800e-04 2.99331703e-03]
[0.2965313  0.40286313 0.19618901 0.10441656]
[0.6346093  0.19324632 0.16175831 0.01038608]
[0.06023459 0.91914423 0.01224211 0.00837907]
[0.84584276 0.12902806 0.00459292 0.02053626]
[0.91740141 0.00308146 0.07470477 0.00481236]
[0.95612957 0.02473853 0.00846435 0.01066755]
[0.70979128 0.25910521 0.01266971 0.0184338 ]
[0.97331985 0.00274755 0.02123641 0.00269619]
[0.06277764 0.87749068 0.04391333 0.01581834]
[0.93269888 0.03233309 0.02284447 0.01212355]
[0.67693353 0.11308793 0.18712557 0.02285296]
[0.63842934 0.01182789 0.34433521 0.00540755]
[0.19992159 0.54584632 0.15570977 0.09852232]
[0.47787876 0.45769625 0.02900695 0.03541804]
[0.85779363 0.02835912 0.06650026 0.04734699]
[0.4352876  0.49123743 0.04112999 0.03234498]
[0.97834851 0.00615466 0.00631575 0.00918108]
[0.97604462 0.00556804 0.00274617 0.01564117]
[0.83699374 0.12232871 0.00434869 0.03632886]
[0.80499761 0.1195

[0.14521507 0.51038445 0.02852655 0.31587393]
[0.47990745 0.06682774 0.44183112 0.01143368]
[0.95880644 0.02983124 0.00218277 0.00917956]
[0.53995953 0.26604921 0.16247225 0.03151901]
[0.01788709 0.97668152 0.00338521 0.00204618]
[0.10419713 0.77464309 0.11389305 0.00726673]
[0.45341885 0.45128336 0.07547631 0.01982148]
[0.72889099 0.00693473 0.05072616 0.21344812]
[0.07960858 0.86957953 0.02640025 0.02441164]
[0.06660556 0.63566053 0.29252402 0.00520989]
[0.80204718 0.15456826 0.03596745 0.00741712]
[0.17157503 0.63554807 0.14637947 0.04649743]
[0.01128136 0.97205163 0.01400938 0.00265763]
[0.2038965  0.75991024 0.03062926 0.005564  ]
[0.0222168  0.49934428 0.45790475 0.02053416]
[0.128861   0.50861067 0.33647966 0.02604868]
[0.02233882 0.01255412 0.96170824 0.00339882]
[0.22588209 0.22540975 0.54301235 0.00569581]
[0.24232988 0.51165904 0.22599713 0.02001395]
[0.47013122 0.43857483 0.07766842 0.01362553]
[0.72021837 0.2216066  0.02025568 0.03791935]
[0.70179151 0.26825973 0.00905397 

[0.62017038 0.34465142 0.0136377  0.02154051]
[0.33785826 0.18004988 0.47188183 0.01021003]
[0.95524234 0.00606153 0.00484764 0.03384849]
[0.94796142 0.03931387 0.00521378 0.00751093]
[0.89728955 0.08775614 0.00611332 0.00884098]
[0.88427506 0.09069482 0.00846301 0.01656711]
[0.74016392 0.04722537 0.18443482 0.02817589]
[9.95112308e-01 7.88506255e-04 1.26856644e-03 2.83061915e-03]
[0.75458736 0.0724954  0.12665513 0.04626211]
[0.96345454 0.00715087 0.02171416 0.00768043]
[0.28896191 0.62645452 0.0691124  0.01547117]
[0.65650683 0.29513034 0.03245716 0.01590567]
[0.89366195 0.02185971 0.0049003  0.07957804]
[0.98746264 0.00206199 0.0011777  0.00929767]
[0.30972628 0.63481441 0.05122214 0.00423716]
[0.96847868 0.01262846 0.00140454 0.01748832]
[0.44737144 0.09129659 0.44066    0.02067198]
[0.65059037 0.12485139 0.21934332 0.00521493]
[0.31736717 0.57033926 0.08028315 0.03201042]
[0.038167   0.86101803 0.09224927 0.0085657 ]
[0.97234929 0.01423659 0.01007804 0.00333608]
[0.39178878 0.3820

[0.91636107 0.04183334 0.01518571 0.02661988]
[0.25812265 0.60214102 0.12915622 0.01058011]
[0.35667939 0.39410253 0.16757095 0.08164713]
[0.83619373 0.14083324 0.01624681 0.00672622]
[0.48935459 0.48636761 0.00664525 0.01763255]
[0.11752381 0.64726204 0.22853108 0.00668307]
[0.61443793 0.33503406 0.04753053 0.00299749]
[0.95319809 0.03090126 0.00541427 0.01048638]
[0.65326115 0.04314315 0.29414697 0.00944873]
[0.58395533 0.37262909 0.01286358 0.030552  ]
[0.02552361 0.29205347 0.66898104 0.01344188]
[0.76260588 0.06123935 0.15172158 0.0244332 ]
[0.8707375  0.09237339 0.03188629 0.00500281]
[9.94105164e-01 7.47793791e-04 2.16864949e-03 2.97839261e-03]
[0.75416329 0.16722702 0.06559257 0.01301712]
[0.91280463 0.00997687 0.07238849 0.00483002]
[0.96603579 0.00990469 0.02111227 0.00294725]
[0.95050417 0.02510002 0.01420343 0.01019238]
[0.29976862 0.57659352 0.10948543 0.01415243]
[0.37912754 0.47752693 0.12191395 0.02143157]
[0.16686422 0.52673681 0.23169927 0.0746997 ]
[0.90738261 0.0029

[0.5806164  0.26485495 0.14743156 0.00709709]
[0.25305029 0.30155934 0.23526402 0.21012635]
[0.12227062 0.84446702 0.02717184 0.00609052]
[0.53708454 0.26217954 0.19285874 0.00787718]
[0.87790862 0.07166612 0.01026051 0.04016475]
[9.93916417e-01 2.25707815e-03 2.91144271e-03 9.15061828e-04]
[0.96523962 0.00846568 0.00935341 0.01694128]
[0.47531868 0.43385836 0.0795612  0.01126177]
[0.31694757 0.1121306  0.56118466 0.00973717]
[0.03224904 0.82348714 0.14034865 0.00391517]
[0.03051853 0.77292164 0.01663697 0.17992286]
[0.06717536 0.89844363 0.02612211 0.0082589 ]
[0.96177814 0.02396539 0.00622307 0.0080334 ]
[0.93394999 0.03937292 0.00849145 0.01818564]
[0.95978402 0.0107891  0.01374551 0.01568137]
[0.948743   0.00274208 0.0171197  0.03139523]
[0.07738293 0.88987188 0.0284383  0.00430689]
[0.50686178 0.46043711 0.01108194 0.02161917]
[0.91841125 0.05959914 0.01549257 0.00649704]
[0.77630918 0.04085548 0.16697705 0.01585829]
[0.25916471 0.56330446 0.16672631 0.01080452]
[0.30157195 0.6753

[0.88684764 0.06434354 0.00773027 0.04107855]
[0.12309408 0.27667704 0.58813426 0.01209462]
[0.81130204 0.15797645 0.00735393 0.02336758]
[0.87638205 0.09053802 0.00966443 0.02341549]
[0.42152276 0.22275933 0.3369514  0.01876651]
[0.01842888 0.40032262 0.56826676 0.01298174]
[0.01972843 0.08271133 0.87226827 0.02529197]
[0.02001465 0.91924408 0.01131306 0.04942821]
[0.6738884  0.30128746 0.0139799  0.01084424]
[0.05466649 0.91755243 0.01192908 0.015852  ]
[0.1847422  0.72069653 0.05730969 0.03725158]
[0.22150531 0.22895431 0.52379696 0.02574342]
[0.18635971 0.55009536 0.11138233 0.1521626 ]
[0.08278831 0.83249826 0.04588496 0.03882847]
[0.8725196  0.05159589 0.06741893 0.00846558]
[0.96862918 0.02466595 0.00450327 0.0022016 ]
[0.64314925 0.3255487  0.02878161 0.00252043]
[0.15469378 0.76509279 0.07425638 0.00595705]
[0.06837688 0.30887717 0.613785   0.00896095]
[0.59974724 0.36134579 0.03344729 0.00545968]
[0.98792223 0.00262305 0.00726914 0.00218558]
[0.019685   0.87410141 0.03426526 

[0.2218275  0.60128526 0.17273337 0.00415387]
[0.94029196 0.05273806 0.00173835 0.00523163]
[0.14794077 0.726498   0.12163114 0.00393009]
[0.1754606  0.61347518 0.16603201 0.04503221]
[0.06294745 0.10859534 0.03765226 0.79080496]
[0.64462287 0.30269609 0.04390653 0.00877451]
[0.36812993 0.04667825 0.56972416 0.01546765]
[0.84633224 0.11973747 0.02478251 0.00914778]
[0.14893012 0.82628678 0.02176877 0.00301433]
[0.0154462  0.09774584 0.88245757 0.00435039]
[0.86359956 0.09060512 0.00580027 0.03999504]
[0.59729399 0.36338881 0.02784134 0.01147586]
[0.33694792 0.64277954 0.00366252 0.01661003]
[0.84335656 0.13766565 0.00754036 0.01143743]
[0.02831129 0.9152187  0.01596516 0.04050485]
[0.97389123 0.01883167 0.00308933 0.00418776]
[0.8565455  0.09176683 0.01050828 0.04117939]
[0.56514759 0.36249368 0.02152593 0.0508328 ]
[0.0326646  0.03613931 0.92712527 0.00407081]
[0.70844551 0.13781018 0.10663128 0.04711303]
[0.84796968 0.13219375 0.00243078 0.01740579]
[0.86281672 0.10930091 0.01489593 

[0.98823455 0.00159829 0.00734462 0.00282253]
[0.91737871 0.00995683 0.05525743 0.01740703]
[0.01851462 0.87239716 0.08867493 0.02041328]
[0.03207879 0.86047004 0.0731107  0.03434047]
[0.37999733 0.58470015 0.02412711 0.01117541]
[0.29130262 0.643473   0.04809237 0.01713201]
[0.98156302 0.00608764 0.00895767 0.00339167]
[0.98039008 0.00961673 0.00265525 0.00733794]
[0.01034362 0.93743581 0.05051717 0.0017034 ]
[0.31018049 0.1019612  0.55792413 0.02993418]
[0.36687847 0.62119676 0.0095748  0.00234997]
[0.00997045 0.91556946 0.01657464 0.05788545]
[0.42759868 0.53526398 0.02736601 0.00977133]
[0.97164736 0.02131804 0.0056289  0.0014057 ]
[0.12079096 0.71769976 0.13592025 0.02558903]
[0.22168651 0.73616658 0.02355928 0.01858763]
[0.9101075  0.04910003 0.00523937 0.0355531 ]
[9.97440877e-01 6.60400766e-04 3.16741524e-04 1.58198113e-03]
[0.97210905 0.01069381 0.00974619 0.00745096]
[0.9459975  0.00312172 0.02747053 0.02341024]
[0.46247099 0.26481539 0.25596813 0.0167455 ]
[0.94407364 0.0292

KeyboardInterrupt: 

In [51]:
df_results.head()

id                                          pred_prob
0  7a44da50  [[0.9758356477707822, 0.011171769639178807, 0....
1  7a44dcf8  [[0.7681146272783964, 0.07101922672307351, 0.1...
2  7a44dd66  [[0.4421420907248543, 0.4960221146720745, 0.05...
3  7a44df46  [[0.042625750023046326, 0.30207018535440266, 0...
4  7a44dfb4  [[0.5118645143800704, 0.26784633945071085, 0.1...

In [45]:
df_results = df_results.pred_prob.apply(lambda prob: pd.Series(list(prob)))

In [48]:
df_results.head()

0         1         2         3
0  0.975836  0.011172  0.007421  0.005572
1  0.768115  0.071019  0.149718  0.011148
2  0.442142  0.496022  0.053872  0.007964
3  0.042626  0.302070  0.635354  0.019950
4  0.511865  0.267846  0.153684  0.066605

In [ ]:
np.savetxt('results.csv', [pred_probas], delimiter=',', fmt='%d')